name: Checks
on:
  push:
  pull_request_target:
    types: [synchronize]

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check if PRs have conflicts
        uses: eps1lon/actions-label-merge-conflict@0273be72a0bbd58fcd71d0d6c02c209b50d1e5e1 # v3.1.0
        if: ${{ github.repository == vars.REPO_MAIN && github.actor != 'dependabot[bot]' }}
        with:
          dirtyLabel: "merge-conflicts"
          repoToken: "${{ secrets.MERGE_CONFLICT_LABEL_PAT }}"
