name: Internationalization
on:
  pull_request:

permissions:
  contents: read

jobs:
  i18n-check:
    name: Check i18n translations
    if: github.event.pull_request.user.login == 'weblate'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: actions/setup-node@v7
        with:
          node-version: 24
      - name: Check translations
        run: node scripts/translation/check-translation-coverage.mts
