name: Internationalization
on:
  push:
    branches:
      - "weblate:*"
  workflow_dispatch:
  pull_request:
    paths:
      - "apps/client/src/translations/**"
      - "apps/website/src/translations/**"
      - "apps/website/src/locales.ts"
      - "packages/commons/src/lib/i18n.ts"
      - "scripts/translation/**"
      - ".github/workflows/i18n.yml"

permissions:
  contents: read

jobs:
  i18n-check:
    name: Check i18n translations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
      - name: Set up node & dependencies
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Check translations
        run: pnpm tsx scripts/translation/check-translation-coverage.ts
